baseurl = "https://AlexG28.github.io/portfolio/"
title = "Aleksandr Gyumushyan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Aleksandr Gyumushyan"
  info = "Junior Software Developer"
  description = "Aleksandr Gyumushyan's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/AlexG28/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/aleksandrgyumushyan/"
[[params.social]]
  name = "Resume"
  icon = "fa-solid fa-file-pdf fa-2x"
  weight = 3
  url = "https://drive.google.com/file/d/1Rf459_zBqk_thjVEMFyjHaunmsJ7iVYR/view?usp=sharing"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 2
  url = "projects/"
[[menu.main]]
  name = "Photography"
  weight = 3
  url = "photography/"
[[menu.main]]
  name = "About"
  weight = 4
  url = "about/"